### ISSUE TITLE
 `get_prebuilts.sh` doesn't handle hyphen characters in the apk file name 

### ISSUE THREAD

**Issue by petefoth** [sfX-android/android_vendor_extendrom#1]
Try to get the latest MicroG GmsCore apk for the MicroG F-Droid repo <https://microg.org/fdroid/repo/com.google.android.gms-204714034.apk>
The relevamt line in packages.txt
```
com.google.android.gms204714034.apk|https://microg.org/fdroid/repo|priv-app|GmsCore.apk;PRESIGNED|true
```

This ends up in vendor/extendrom/prebuilts as `204714034.apk`  and appears to be corrupt :)

**Comment by steadfasterX** [comment]
thy for the report. fixed by: https://github.com/sfX-android/android_vendor_extendrom/commit/308c364faedd505044cbdb285c3fc475c1733471
