### ISSUE TITLE
lack of vendorsetup.sh

### ISSUE THREAD

**Issue by Geofferey** [sfX-android/android_vendor_extendrom#11]
What do I do if there is no vendorsetup.sh? 

I tried to have your Android.mk call it using $(shell ) but it didn't like that lol.

**Comment by Geofferey** [comment]
I tried that and it appears to have zero effect. I'm trying this on omnirom. I have not seen vendorsetup.sh like lineage.

**Comment by steadfasterX** [comment]
can you share your device tree repo?

**Comment by Geofferey** [comment]
https://github.com/Geofferey/omni_device_oneplus_oneplus7pro

I think I figured it out, feel kinda stupid now as well. I rebooted my system and when I run `source build/envsetup.sh` again I see the magic ;). Hopefully I don't run into anymore issues. I'm trying to use your solution because it does seem robust and my solution is admittedly unsustainable for any future.

**Comment by steadfasterX** [comment]
I'm glad it works now :) if you encounter any further issues open another issue or contact me at Matrix (https://matrix.to/#/#sfX_Android:matrix.org?via=binbash.rocks&via=matrix.org) or Telegram (http://t.me/sfX_Android)
