### ISSUE TITLE
AdAway requires signed key?

### ISSUE THREAD

**Issue by OctoNezd** [sfX-android/android_vendor_extendrom#12]
I assume this is a bug, because it is the only package with user-keys/shared instead of PRESIGNED and nothing about that is mentioned in https://github.com/sfX-android/android_vendor_extendrom/wiki/EXTENDROM_PACKAGES

**Comment by steadfasterX** [comment]
thx for reporting. Fixed in https://github.com/sfX-android/android_vendor_extendrom/commit/7ddcabbc14cc3990245c858addeabc2f1f374075#diff-b913bcd7262c28853a2a2596c2d7b22c72f11f4c547ce86b25019a35ae238f78 :)
