### ISSUE TITLE
Use a 'production' version of Lawnchair

### ISSUE THREAD

**Issue by petefoth** [sfX-android/android_vendor_extendrom#2]
The Lawnchair builds available on APK Mirror are C/I builds. When they are installed, when they are first used, or when set as default home screen / launcher, they display a popup message saying something like "Please don't use CI builds in production: use official releases". 

Solution is to pick up the version from the Google Play store (via Aurora Store app), and use that version instead

**Comment by steadfasterX** [comment]
merged ;)
