### ISSUE TITLE
Clarification needed for mkbootimg.mk instructions

### ISSUE THREAD

**Issue by Gooberpatrol66** [sfX-android/android_vendor_extendrom#20]
`copy the whole (matching to your device..) $(INSTALLED_BOOTIMAGE_TARGET): block from build/core/Makefile`

my Makefile has multiple $(INSTALLED_BOOTIMAGE_TARGET):  blocks in it. How do I know which one to copy?

`add: @/bin/bash $(ROOT_BOOT_BIN) $$PWD/$@ in the block of $(INSTALLED_BOOTIMAGE_TARGET): , AFTER the MKBOOTIMG line and BEFORE any AVB line`

none of the $(INSTALLED_BOOTIMAGE_TARGET):  blocks in the file contain a MKBOOTIMG line.

there is a block called $(INSTALLED_VENDOR_BOOTIMAGE_TARGET): which contains a MKBOOTIMG line.

**Comment by steadfasterX** [comment]
well that depends usually on e.g. the Android version and device vendor

**Comment by Gooberpatrol66** [comment]
It's lineageos 19.1, oneplus nord n200

**Comment by steadfasterX** [comment]
check out https://github.com/sfX-android/android_vendor_extendrom/wiki/EXTENDROM_PREROOT_BOOT-NG
