### ISSUE TITLE
Changes needed in 'Phonesky' for LOS 20.0

### ISSUE THREAD

**Issue by petefoth** [sfX-android/android_vendor_extendrom#24]
When I made a custom build of Lineageos for Microg including the `Phonesky` extendrom package, the build succeeded, but the built ROM bootlooped.

The problem is that for Android 13 / LOS 20 `Phonesky` needs some additional permissions in `extra/com.android.vending.xml`

I found details of the fix in [this commit in the MinMicrog github repo](https://github.com/FriendlyNeighborhoodShane/MinMicroG/commit/91fefd0bbce3407e5f65c752fbaf88071948340f)

Making those changes allowed the ROM to boot successfully. However, I didn't save the changes, and removed `Phonesky` from my build, while I was trying to get round the "missing apps" problem (see #23), so I can't submit working patches (or a PR ;) )

**Comment by steadfasterX** [comment]
you have used [this](https://github.com/FriendlyNeighborhoodShane/MinMicroG/commit/91fefd0bbce3407e5f65c752fbaf88071948340f) fix and it worked? but then that means we just need to add these afaiu? Or is there anything else missing you can't rem?

**Comment by petefoth** [comment]
> you have used [this](https://github.com/FriendlyNeighborhoodShane/MinMicroG/commit/91fefd0bbce3407e5f65c752fbaf88071948340f) fix and it worked?

Not really. I haven't included Phonesky in my builds before. I was just experimenting with including it in one of my recent builds. the build didn't boot, so I made a build with this fix and the fixed build booted, but there were other  problems (the missing, perhaps unsigned apps problem). I didn't try to test Phonesky. 

When I made further builds to try and fix the missing apps problem, I didn't include Phonesky in the build (in case it was contributing to the missing apps problem). So I **think** it should be OK to just add these permissions, but I haven't really tested that. Tha'ts why I raised an issue, rather than submitting a patch.

**Comment by steadfasterX** [comment]
aha ok thanks for clarification!

**Comment by petefoth** [comment]
I have tried making a build including Phonesky, with the extra permissions added, and tried `<cert-path>` set to both  `PRESIGNED` and `user-keys/platform`. In both cases the phone boot loops after displaying the Lineage startup animation.

So I have no idea what the way forward is for Phonesky an LOS 20 / Android 13 builds. I'm giving up on Phonesky in my builds I'm afraid.

**Comment by steadfasterX** [comment]
should be fixed with https://github.com/sfX-android/android_vendor_extendrom/commit/9a9c16aa7a18aaed49f909694b04abcf30fcad87#diff-7f43aeb7b1e6b1bb63ca67db66edac4cbd97ec797472054e7d23812ba9dab65c
