### ISSUE TITLE
LOS 19.1 extendrom builds fail due to `--enforce-uses-libraries`

### ISSUE THREAD

**Issue by petefoth** [sfX-android/android_vendor_extendrom#25]
I got a build error below when building extendrom targets (repeated for most of the prebuilt targets)
`error: mismatch in the <uses-library> tags between the build system and the manifest:`

The interesting bit from the full error message is 
```
- to temporarily disable the check on command line, rebuild with RELAX_USES_LIBRARY_CHECK=true 
  (this will set compiler filter "verify" and disable AOT-compilation in dexpreopt)
- to temporarily disable the check for the whole product, set PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := 
  true in the product makefiles
- to fix the check, make build system properties coherent with the manifest
- see build/make/Changes.md for details
```
The file `build/make/Changes.md` says
```
* Android.bp property: `provides_uses_lib`
* Android.mk variable: `LOCAL_PROVIDES_USES_LIBRARY`

It is possible to disable the check on a per-module basis. When doing that it is
also recommended to disable dexpreopt, as disabling a failed check will result
in incorrect class loader context recorded in the .odex file, which will cause
class loader context mismatch and dexopt at first boot.

* Android.bp property: `enforce_uses_lib`
* Android.mk variable: `LOCAL_ENFORCE_USES_LIBRARIES`
```
I "fixed" my build by calling `export RELAX_USES_LIBRARY_CHECK=true` (as suggested by the error message), then `mka bacon`.  I now put that `export` in my `vendorsetup.sh` and builds seem to work fine. 

The effect of the fix is to disable the check for the whole build. A **better** "fix" is by changing `/tools/extract_utils.sh` to add the line `LOCAL_ENFORCE_USES_LIBRARIES := false` to each module in `Android.mk`.

I thought about trying to make some changes in my `extendrom` fork, but decided that I'm not a shell programmer, and I chose to get on with making builds using the workaround

----
Here's the full error text
```
 66% 93070/139054] Verifying uses-libraries: vendor/extendrom/prebuilt/at.bitfire.davdroid_LATEST.apk
FAILED: out/target/common/obj/APPS/DAVx5_intermediates/enforce_uses_libraries.status
/bin/bash -c "(rm -f out/target/common/obj/APPS/DAVx5_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py 	  --enforce-uses-libraries 	  --enforce-uses-libraries-status out/target/common/obj/APPS/DAVx5_intermediates/enforce_uses_libraries.status 	  --aapt out/host/linux-x86/bin/aapt 	   	   	   	   	  vendor/extendrom/prebuilt/at.bitfire.davdroid_LATEST.apk )"
error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: []
	- optional libraries in build system: []
	                 vs. in the manifest: [androidx.window.extensions, androidx.window.sidecar]
	- tags in the manifest (vendor/extendrom/prebuilt/at.bitfire.davdroid_LATEST.apk):
		uses-library-not-required:'androidx.window.extensions'		uses-library-not-required:'androidx.window.sidecar'
note: the following options are available:
	- to temporarily disable the check on command line, rebuild with RELAX_USES_LIBRARY_CHECK=true (this will set compiler filter "verify" and disable AOT-compilation in dexpreopt)
	- to temporarily disable the check for the whole product, set PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true in the product makefiles
	- to fix the check, make build system properties coherent with the manifest
	- see build/make/Changes.md for details

22:55:00 ninja failed with: exit status 1

#### failed to build some targets (01:08:45 (hh:mm:ss)) ####
```

**Comment by steadfasterX** [comment]
so from what I understand from that Changes.md :

~~~
In such cases it is possible to tell the build system that the library provides a
`<uses-library>` with a given name (however, this is discouraged and will be
deprecated in the future, and it is recommended to fix the underlying problem):

[...]
* Android.mk variable: `LOCAL_PROVIDES_USES_LIBRARY`
~~~

so first of all we need `LOCAL_PROVIDES_USES_LIBRARY := true`  and then:

~~~
It is possible to disable the check on a per-module basis. When doing that it is
also recommended to disable dexpreopt, as disabling a failed check will result
in incorrect class loader context recorded in the .odex file, which will cause
class loader context mismatch and dexopt at first boot.

[...]
* Android.mk variable: `LOCAL_ENFORCE_USES_LIBRARIES`
~~~

so **additionally** we would need: `LOCAL_ENFORCE_USES_LIBRARIES := true`

as mentioned there the whole stuff might get deprecated later but I am fine with adding the above for the moment. Just I cannot test atm if the above 2 vars are correct and working as I assume or not.

e.g. I assume setting these both vars to `true` while you mentioned `false`..

**Comment by petefoth** [comment]
My understanding was different. With my workaround' I am disabling the `enforce_uses_libraries` check for the whole build

We don't have the needed information to set the `LOCAL_PROVIDES_USES_LIBRARY` value(s) correctly for our downloaded APKs. So we disable the check for them by setting `LOCAL_ENFORCE_USES_LIBRARIES := false` for each of them. That way the build system will continue to do the check for the rest of the modules in the build, but not for our modules, which would fail the check.

So I think we just add the line `LOCAL_ENFORCE_USES_LIBRARIES := false` for each module when we create the makefile

**Comment by steadfasterX** [comment]
ah ok nice thanks. can you test that?

you would just need to adjust https://github.com/sfX-android/android_vendor_extendrom/blob/main/tools/extract_utils.sh#L212

simply add:
`LOCAL_ENFORCE_USES_LIBRARIES := false` 
before the `${EXTRA}` line  and it will be added to all generated module definitions in Android.mk

btw:  will this have any impact on lower android versions? like those where that flag does not exist?

**Comment by petefoth** [comment]
> simply add: `LOCAL_ENFORCE_USES_LIBRARIES := false` before the `${EXTRA}` line and it will be added to all generated module definitions in Android.mk

I'll give that a try, and report back


> btw: will this have any impact on lower android versions? like those where that flag does not exist (or does that exist since always?)?

I'm just about to kick off an 18.1 build, to check the recent changes haven't broken anything there. I'll make this change and see what happens. I'm building locally so the results may take a few days to arrive ;)

**Comment by steadfasterX** [comment]
cool thanks for your help here ;)

**Comment by petefoth** [comment]
> I'm just about to kick off an 18.1 build, to check the recent changes haven't broken anything there. I'll make this change and see what happens. I'm building locally so the results may take a few days to arrive ;)

The suggested fix works for LOS 20 builds, but it seems to break LOS 18 builds which fail with the following error:

```
[ 56% 61712/109415] Verifying uses-libraries: vendor/extendrom/prebuilt/com.aurora.store_LATEST
FAILED: out/target/common/obj/APPS/AuroraStore_intermediates/enforce_uses_libraries.timestamp
/bin/bash -c "(aapt_binary=out/host/linux-x86/bin/aapt    uses_library_names=\"\"         optional_uses_library_names=\"\"        build/make/core/verify_uses_libraries.sh vendor/extendrom/prebuilt/com.aurora.store_LATEST.apk ) && (touch out/target/common/obj/APPS/AuroraStore_intermediates/enforce_uses_libraries.timestamp )"
LOCAL_OPTIONAL_USES_LIBRARIES ()  do not match (androidx.window.extensions androidx.window.sidecar) in manifest for vendor/extendrom/prebuilt/com.aurora.store_LATEST.apk
```
So the fix needs to be made conditional on Android version

**Comment by steadfasterX** [comment]
ah well I thought that this might happen..

**Comment by petefoth** [comment]
>  Does that flag start in LOS 20 first or is it in 19.1 as well? hm that flag even exist in Android 10..

I didn't see a problem until 19.1. 18.1 builds were OK without the workaround. 

According to  https://developer.android.com/about/versions/12/behavior-changes-12
> **Vendor-supplied native shared libraries**
>
> [Non-NDK native shared libraries](https://source.android.com/devices/tech/config/namespaces_libraries#adding-additional-native-libraries) that are provided by silicon vendors or device manufacturers are not accessible by default if the app is targeting Android 12 (API level 31) or higher. The libraries are accessible only when they are explicitly requested using the [`<uses-native-library>`](https://developer.android.com/guide/topics/manifest/uses-native-library-element) tag.
>
>If the app is targeting Android 11 (API level 30) or lower, the <uses-native-library> tag is not required. In that case, any native shared library is accessible regardless of whether it is an NDK library.

So I **think** this is happening because the build tool is now checking that pre-built apps did request the libraries they use. 

Whatever, the workaround / fix needed for the 19.1 builds breaks my 18.1 builds.

**Comment by OctoNezd** [comment]
I implemented that in my custom vendor prebuilts script using `aapt` tool:
```python3
def get_requirements(destination):
    requirements_txt = subprocess.check_output(
        ["aapt", "dump", "badging" ,destination]).decode()
    requirements_optional = []
    requirements = []
    for line in requirements_txt.split("\n"):
        if line.startswith("uses-library-not-required:"):
            requirements_optional.append(line.split(":")[1].strip("'"))
        elif line.startswith("uses-library:"):
            requirements.append(line.split(":")[1].strip("'"))
    return {"required": requirements, "optional": requirements_optional}
```

Though I am not sure if I implemented that correctly, given that Fenix just doesn't appear in OS or any of logs minus the fact that it is included and lies in /system/app.

**Comment by petefoth** [comment]
#29 does **not** fix this problem. I reverted the commit that might have have fixed this because it breaks LOS 18 builds: see
- [this comment](https://github.com/sfX-android/android_vendor_extendrom/pull/29#issuecomment-1347825640)
- [this commit](https://github.com/sfX-android/android_vendor_extendrom/commit/a555a079f67343c46a60ceff50dde9a7998f93f6)

This issue should be re-opened as the problem

**Comment by steadfasterX** [comment]
yea the issue gets closed due to the PR merge - unintended. I currently work on a fix for this issue which looks good so far but I am not sure if that breaks older android versions.

**Comment by steadfasterX** [comment]
related background:

- https://source.android.com/docs/core/runtime/art-class-loader-context?hl=en#fixing-breakages
- https://android.googlesource.com/platform//build/+/345294f459ec83599053b308085d45bce0c1e788/core/verify_uses_libraries.sh <br/> -> later implementation of the same check / badging:<br/> https://cs.android.com/android/platform/superproject/+/android-13.0.0_r30:build/soong/scripts/manifest_check.py;l=171
