### ISSUE TITLE
Allow combinations of additional F-Droid repos

### ISSUE THREAD

**Issue by petefoth** [sfX-android/android_vendor_extendrom#26]
The Problem
-
The `additional_repos.xml` module adds some popular F-Droid repos which the F-Droid app uses to install and update the apps published in those repos.

We are adding new modules (Bromite browser, more MicroG components) which also have F-Droid repos where updates are releases are published.

Users need to be able to combine these lists of repos and use the combined list in their builds, by including them in the file `additional_repos.xml` (which the build system places in `/vendor/etc/org.fdroid.fdroid`).

Upstream [F-Droid Android client app](https://gitlab.com/fdroid/fdroidclient/-/blob/master/app/src/main/java/org/fdroid/fdroid/data/DBHelper.java#L135) looks in the `etc/org.fdroid.fdroid` subdirectory of a number of different directories `(/system, /product, /vendor, /odm, /oem`) for **a single file** named `additional_repos.txt`, and adds the repo items defined in that file.

Proposed solution
-
Have a number of different `F-DroidRepos` targets: **one for each possible combination**
1. `Extra_FDroidRepos`: (the current `additional_repos.xml`file / target )
2. `Microg_FDroidRepos`: contains `microG F-Droid repo` and  `microG F-Droid archive`
3. `Bromite_FDroidRepos`:  contains `Bromite F-Droid repo`
4. `MicrogBromite_FDroidRepos`: 2 and 3 combined
5. `All_FDroidRepos`: 1, 2 and 3 combined

This is not the most elegant solution - see below - but it is the one that involves the least work / fewest changes. It also gives a clear pattern for how users can add their own additional repos in combination with existing ones

Alternative solutions
-
1. Change upstream: Make changes in the F-Droid android client, so that , instead of including repos speciied only in a file named  `additional_repos.xml`,  it includes content from all files matching the regexp `*_repos.xml` 
    - pro: very flexible; no inter-dependencies between modules that have associated F-Droid repos
    - con: needs java code to be written (and tested and inspected); no guarantee upstream would accept the change
2. Add code in this project to combine information from multiple   `*_repo_items.xml` into a single `additional_repos.xml` file
    - pro: very flexible; easy to add more repos for new  targets
    - con: more code (shell scripts and / or makefiles) to be written, inspected, and tested (and to introduce bugs :) ) I don't have the skills to write that code

**Comment by steadfasterX** [comment]
check out https://github.com/sfX-android/android_vendor_extendrom/tree/split_fdroid_repos

the commit https://github.com/sfX-android/android_vendor_extendrom/commit/338accb328b441e590e547e35b3b2b1e3df54f43 introduces the following:

- additional_repos.xml does not contain the bromite and microg repos
- the LOCAL_MODULE config has been removed from the extra/Android.mk
- a new extendrom flag has been added: `EXTENDROM_FDROID_REPOS` where you can define space separated as many xmls as you like! they will be all concatenated :)
- a new directory `fdroid_repos/` should contain all fdroid xml files from now on

Of course the above has been tested and it worked for me.. :)

the above is not yet merged, what do you think about it?

**Comment by petefoth** [comment]
Nice! It gives us Alternative solution 1 without bothering upstream

I'd be very happy for you to merge it **but** I just finished and committed changes in the `pf-upstream-changes` branch (and therefore the PR) to split the repos as you have done. So there may be conflicts :( Should I revert those commits in my branch or can you handle them?
