### ISSUE TITLE
MicroG  GmsCore: replace /e/ version with  LineageOS for microG 

### ISSUE THREAD

**Issue by petefoth** [sfX-android/android_vendor_extendrom#3]
Current /e/ OS ROMs contain a version of MicroG GmsCore that does not include the Exposure Notification framework, used by Covid contact tracing apps. Their preferred method of installing the EN Framework is to use their Apps app store, which is buggy, and which is not possible when Apps is removed from the ROM. It is also not clear whether - or how - /e/ will provide updates to the EN Framework in future.

Solution is to 
- use the version of GmsCore used by [LineageOS for microG ](https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/tree/master/GmsCore)
- add the MicroG F-Droid repos to the `additional_repos` package/module

**Comment by steadfasterX** [comment]
u mentioned in your PR that this caused issues? has this been fixed? if so pls do another PR for that one, thx

**Comment by petefoth** [comment]
> u mentioned in your PR that this caused issues? has this been fixed? if so pls do another PR for that one, thx

No it's not fixed. Getting a working version of GmsCore in my builds is proving to be really problematic. It doesn't help that the /e/ version isn't currently working. When I eventually solve  this I will raise a new PR
