### ISSUE TITLE
Change the split repos implementation...

### ISSUE THREAD

**Issue by petefoth** [sfX-android/android_vendor_extendrom#31]
... to allow the `additional_repos.xml`module to replace LineageOS for MicroG's version

I'm using this project to make customised builds ofLineageOS for MicroG.

L4M includes F-Droid, and their own `additional_repos.xml` module, containing only the Microg repos. I would like to be able to replace their module, with the 'split repos' version from here. I think that can be done by writing a `LOCAL_OVERRIDES_PACKAGES` line in `F_WRITE_MAKEFILE_FDROID()`

**Comment by steadfasterX** [comment]
Ig that's done by: https://github.com/sfX-android/android_vendor_extendrom/wiki/EXTENDROM_FDROID_REPOS

if not feel free to re-open ;)
