### ISSUE TITLE
magisk: cannot find patch file

### ISSUE THREAD

**Issue by ClawOfDead** [sfX-android/android_vendor_extendrom#35]
I got this error when trying to patch magisk boot all is setup but seems the path has a problem if I change the code with chatgpt it runs forever.

```
[PATCHER]  ... ended with errorcode 2/0
patch: **** Can't open patch file /home/clawdev/A9//home/clawdev/A9/vendor/extendrom/config/magisk/patches/0001-build_make_tools_releasetools_common.patch : No such file or directory
[PATCHER]  FATAL ERROR occured while applying >0001-build_make_tools_releasetools_common.patch<!!!

bash stack trace (first occurence is likely where you should look at):

ERROR: last command ended with status >3< at line >427<
[MAGISK] Injecting Magisk patcher ended with 3
```

**Comment by steadfasterX** [comment]
Thanks for your report. In order to help share the whole(!) output when executing 

`vendor/extendrom/er.sh`

**Comment by 2lucem2** [comment]
Ran into the same problem today. Fixed it by replacing line `70` in `vendor/extendrom/tools/apply_patches.sh`:
Replace `P=$(echo "$p" | sed 's#^#-i '$(pwd)'/#g;s/:project#/ -d /g')` with `P=$(echo "$p" | sed 's#^#-i ''/#g;s/:project#/ -d /g')`

**Comment by ClawOfDead** [comment]
So build went fine with the replacement line till near the end (99%).. but failed before building the update img and I took flashallfastboot to try and nothing about magisk was done. :/

Here are the logs I got:

building image from target_files RECOVERY...
building image from target_files BOOT...
Traceback (most recent call last):
  File "build/make/tools/releasetools/make_recovery_patch", line 55, in <module>
    main(sys.argv[1:])
  File "build/make/tools/releasetools/make_recovery_patch", line 42, in main
    input_dir, "BOOT")
  File "/home/clawdev/A9/build/make/tools/releasetools/common.py", line 577, in GetBootableImage
    info_dict, has_ramdisk, two_step_image)
  File "/home/clawdev/A9/build/make/tools/releasetools/common.py", line 516, in _BuildBootableImage
    RunAndCheckOutput(mpatcher, verbose=True, env={'system_root_image': info_dict.get("system_root_image", "false")})
NameError: global name 'RunAndCheckOutput' is not defined
[ 99% 99683/99685] build out/target/product/a95xf1/a95xf1-fastboot-flashall-20231023.zip
install out/target/product/a95xf1/a95xf1-fastboot-flashall-20231023.zip
  adding: boot.img (deflated 1%)
  adding: dt.img (deflated 74%)
  adding: recovery.img (deflated 1%)
  adding: android-info.txt (deflated 7%)
  adding: system.img (deflated 56%)
  adding: vendor.img (deflated 60%)
  adding: product.img (deflated 18%)
  adding: dtbo.img (deflated 58%)
  adding: vbmeta.img (deflated 99%)
  adding: android-info.txt (deflated 7%)
  adding: boot.img (deflated 1%)
  adding: bootloader.img (deflated 2%)
  adding: dt.img (deflated 74%)
  adding: dtbo.img (deflated 58%)
  adding: flash-all.bat (deflated 57%)
  adding: flash-all.sh (deflated 59%)
  adding: logo.img (deflated 93%)
  adding: odm.img (deflated 78%)
  adding: product.img (deflated 18%)
  adding: recovery.img (deflated 1%)
  adding: system.img (deflated 56%)
  adding: vbmeta.img (deflated 99%)
  adding: vendor.img (deflated 60%)
ninja: build stopped: subcommand failed.
08:30:23 ninja failed with: exit status 1

**Comment by ClawOfDead** [comment]
************************************************** STARTING EXTENDROM **************************************************


extendrom version: HEAD 42177f6 



ENABLE_EXTENDROM: true
EXTENDROM_PREROOT_BOOT: true
EXTENDROM_PACKAGES: Magisk
EOS_EDITION: 
EXTENDROM_SIGNING_PATCHES: 
EXTENDROM_SIGNATURE_SPOOFING: 
EXTENDROM_SIGSPOOF_RESET: 
EXTENDROM_SIGSPOOF_FORCE_PDIR: 
EXTENDROM_TARGET_VERSION: 9
EXTENDROM_TARGET_PRODUCT: a95xf1
hardware/amlogic/wifi/configs/wifi.mk:43: warning: WIFI_MOUDLE is multiwifi
hardware/amlogic/wifi/configs/wifi.mk:47: warning: WIFI_BUILD_IN is false
hardware/amlogic/bluetooth/configs/bluetooth.mk:20: warning: BLUETOOTH_MODULE is BCMBT
hardware/amlogic/bluetooth/configs/bluetooth.mk:24: warning: BLUETOOTH_INF is not set
SRC_TOP: /home/clawdev/A9/
hardware/amlogic/wifi/configs/wifi.mk:43: warning: WIFI_MOUDLE is multiwifi
hardware/amlogic/wifi/configs/wifi.mk:47: warning: WIFI_BUILD_IN is false
hardware/amlogic/bluetooth/configs/bluetooth.mk:20: warning: BLUETOOTH_MODULE is BCMBT
hardware/amlogic/bluetooth/configs/bluetooth.mk:24: warning: BLUETOOTH_INF is not set
EXTENDROM_PRODUCT_DEVICE=
EXTENDROM_BOOT_DEBUG=
EXTENDROM_DEBUG_PATH=/data/vendor_de (will be suffixed with /boot_debug)
EXTENDROM_DEBUG_PATH_SIZE_FULL=5000 KB
EXTENDROM_DEBUG_PATH_SIZE_CRASH=500 KB
EXTENDROM_DEBUG_PATH_SIZE_KERNEL=500 KB
EXTENDROM_DEBUG_PATH_SIZE_SELINUX=500 KB
/home/clawdev/A9/out/host/linux-x86/bin/aapt
[F_GET_GPG_KEYS] ... skipping already imported gpg pub key (7A029E54DD5DCE7A)
[F_GET_GPG_KEYS] ... skipping already imported gpg pub key (22F796D6E62E6625A0BCEFEA7F979A66F3E08422)
[get_packages] ... skipping F-Droid as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping F-Droid_v1.16.3 as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping F-DroidPrivilegedExtension_pb as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping AuroraStore as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping AuroraServices as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping AdAway as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping DNS66 as not requested by EXTENDROM_PACKAGES
[download_package] ... downloading package: Magisk.v26.3.apk
[get_packages] ... target package: vendor/extendrom/prebuilt/Magisk.apk

[get_packages] ... skipping SignMagisk as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping Magisk_v26.2 as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping SignMagisk_v26.2 as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping Magisk_v26.1 as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping SignMagisk_v26.1 as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping Magisk_v25.2 as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping SignMagisk_v25.2 as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping Magisk_v24.3 as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping SignMagisk_v24.3 as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping Magisk_v23.0 as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping SignMagisk_v23.0 as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping Magisk_v22.1 as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping SignMagisk_v22.1 as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping Phonesky as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping Phonesky_AXP-OS as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping MicrogGmsCore as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping MicrogGmsCore_GH as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping MicrogGmsCore_unified-latest as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping GsfProxy as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping GsfProxy_GH as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping FakeStore as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping FakeStore_GH as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping NominatimBackend as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping MozillaNlpBackend as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping DroidGuard as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping OpenCamera as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping opencamera_j5_latest as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping SimpleLauncher as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping Omega as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping NeoLauncher-latest as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping NeoLauncher as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping Lawnchair-stable as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping Lawnchair-latest as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping OpenLauncher as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping BlissLauncher as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping K9-Mail-latest as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping FairEmail as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping Fennec as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping QKSMS as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping FFUpdater as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping ICSx5 as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping DAVx5 as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping NextCloud as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping Cromite_arm64 as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping Etar as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping OpenTasks as not requested by EXTENDROM_PACKAGES
[get_packages] ... skipping NextCloudNotes as not requested by EXTENDROM_PACKAGES
[MAGISK] preparing the root process as requested


***************************************************************************
WARNING: EXTENDROM sources are already patched!
If you want to force patching remove the indicator file:
./vendor/extendrom/config/magisk/patches/EXTENDROM_PATCHER_DONE
***************************************************************************


[MAGISK] Injecting Magisk patcher ended with 0
[MAGISK] ... Magisk found!
[MAGISK] ... MAGISK_TARGET_ARCH specified as arm64
[MAGISK] preparing root finished
[main] Writing makefiles (if needed)
[F_WRITE_MAKEFILE] ... skipping AuroraServices as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping GsfProxy_GH as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping Lawnchair-latest as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping Lawnchair-stable as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping Magisk_v22.1 (Magisk is not allowed to be a system app)
[F_WRITE_MAKEFILE] ... skipping SignMagisk_v22.1 (Magisk is not allowed to be a system app)
[F_WRITE_MAKEFILE] ... skipping Magisk_v23.0 (Magisk is not allowed to be a system app)
[F_WRITE_MAKEFILE] ... skipping SignMagisk_v23.0 (Magisk is not allowed to be a system app)
[F_WRITE_MAKEFILE] ... skipping Magisk_v24.3 (Magisk is not allowed to be a system app)
[F_WRITE_MAKEFILE] ... skipping SignMagisk_v24.3 (Magisk is not allowed to be a system app)
[F_WRITE_MAKEFILE] ... skipping Magisk_v25.2 (Magisk is not allowed to be a system app)
[F_WRITE_MAKEFILE] ... skipping SignMagisk_v25.2 (Magisk is not allowed to be a system app)
[F_WRITE_MAKEFILE] ... skipping Magisk_v26.1 (Magisk is not allowed to be a system app)
[F_WRITE_MAKEFILE] ... skipping SignMagisk_v26.1 (Magisk is not allowed to be a system app)
[F_WRITE_MAKEFILE] ... skipping Magisk_v26.2 (Magisk is not allowed to be a system app)
[F_WRITE_MAKEFILE] ... skipping SignMagisk_v26.2 (Magisk is not allowed to be a system app)
[F_WRITE_MAKEFILE] ... skipping Magisk (Magisk is not allowed to be a system app)
[F_WRITE_MAKEFILE] ... skipping SignMagisk (Magisk is not allowed to be a system app)
[F_WRITE_MAKEFILE] ... skipping NeoLauncher as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping Omega as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping Phonesky as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping Phonesky_AXP-OS as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping Cromite_arm64 as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping DAVx5 as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping ICSx5 as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping FakeStore as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping FakeStore_GH as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping AuroraStore as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping OpenLauncher as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping K9-Mail-latest as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping MicrogGmsCore_unified-latest as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping MicrogGmsCore_GH as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping MicrogGmsCore as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping GsfProxy as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping QKSMS as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping NextCloud as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping NeoLauncher-latest as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping SimpleLauncher as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping FFUpdater as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping FairEmail as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping BlissLauncher as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping NextCloudNotes as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping OpenCamera as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping opencamera_j5_latest as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping AdAway as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping OpenTasks as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping F-DroidPrivilegedExtension_pb as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping F-Droid_v1.16.3 as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping F-Droid as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping DNS66 as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping DroidGuard as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping MozillaNlpBackend as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping NominatimBackend as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping Fennec as not requested by EXTENDROM_PACKAGES
[F_WRITE_MAKEFILE] ... skipping Etar as not requested by EXTENDROM_PACKAGES
here is the output from er.sh too

************************************************** EXTENDROM FINISHED **************************************************

**Comment by steadfasterX** [comment]
@ClawOfDead your issue is related to

`NameError: global name 'RunAndCheckOutput' is not defined` 

which means I need to adjust the patch for Android 9 it seems. Will let you know when you can test again
