### ISSUE TITLE
Add some more alternatives to /e/'s system apps

### ISSUE THREAD

**Issue by petefoth** [sfX-android/android_vendor_extendrom#4]
I will include the following in my custom ROMs. Adding them here will allow others to use them in their ROMs if they choose, without needing to fork this repo. All are available in the F-Droid repo
- Email: K-9 Mail (forked by /e/ for their Mail app)
- Messaging: QKSMS (forked by /e/ for their Message app)
- Browser: Fennec-FDroid (because I prefer Mozilla-based browsers)
- ETAR (forked by /e/ for their Calendar app)

**Comment by steadfasterX** [comment]
merged ;)
