### ISSUE TITLE
[FR] Lineage 21 / Android 14 support

### ISSUE THREAD

**Issue by linux-colonel** [sfX-android/android_vendor_extendrom#43]
# Description
When attempting to set up, I noticed that vendorsetup.sh is gone in Lineage 21.  It's the preferred way to install extendrom.  What line can I add in device.mk to get it to execute er.sh at the right time?

# Target version
LineageOS 21 / Android 14

_What Android version should support that feature (add an `x` within the `[ ]` brackets, select all that should apply):_

- [ ] Android 7
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12
- [ ] Android 13
- [X] Android 14

_What custom OS should support that feature (add an `x` within the `[ ]` brackets, select / add all that should apply):_

- [X] Lineage OS
- [ ] AXP.OS
- [ ] AOSP
- [ ] ...

# Note

_when sharing logs it is strongly recommended 
using [github gists](https://gists.github.com)_

**Comment by steadfasterX** [comment]
even though the usage of vendorsetup.sh is depcrated since A10 it still works and is available in LOS 21 as well:

https://github.com/LineageOS/android_build/blob/lineage-21.0/envsetup.sh#L2078-L2088

**Comment by linux-colonel** [comment]
Thanks!  I'll create `vendorsetup.sh` and the build should execute it.

**Comment by steadfasterX** [comment]
yes. just ensure u follow https://github.com/sfX-android/android_vendor_extendrom/wiki/Setup#vendorsetupsh
